# Generated by Django 6.0.7 on 2026-07-29 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionslot',
            constraint=models.UniqueConstraint(fields=('counselor', 'slot_datetime'), name='unique_counselor_slot_datetime'),
        ),
    ]
