# Generated by Django 6.0.7 on 2026-07-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(max_length=30, unique=True)),
                ('real_name_encrypted', models.TextField()),
                ('real_email_encrypted', models.TextField(blank=True, default='')),
                ('encryption_iv', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alias_mapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
