# Generated by Django 6.0.7 on 2026-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_alias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
